### ISSUE TITLE
Does not support "parent" element

### ISSUE THREAD

**Issue by ghost** [rosstuck/ConverterSite#2]
When converting from XML to YAML, the "parent" element seems to be ignored. 

eg.

```
<service id="my.rabbitmq.producer" parent="old_sound_rabbit_mq.send_mail_producer" >
            <call method="setContentType" >
                <argument>application/json</argument>
            </call>
        </service>
```

results in 

```
my.rabbitmq.producer:
        calls:
            - [setContentType, [application/json]]
```

**Comment by rosstuck** [comment]
Hi @sgrabowski, thanks for taking the time to let me know! 

This is a known issue which appears to be upstream in Symfony. See https://github.com/rosstuck/TuckConverterBundle/issues/15 for more details.

I'm going to close this issue as a duplicate for now, but feel free to respond on the other if you have anything to add. Thanks again!
